<#
.SYNOPSIS
  Registers reyd to start at login as a Windows Scheduled Task.

.DESCRIPTION
  The daemon has to be running for the phone to reach anything, and remembering to
  start it defeats the point of the product (docs/decisions.md D-002). A Scheduled
  Task is used rather than a real Windows service because reyd must run as YOU:
  it inherits your Claude credentials from %USERPROFILE%\.claude and needs access
  to your project folders. A LocalSystem service would have neither.

  The password is read from a file rather than baked into the task definition, so
  it never appears in Task Scheduler's XML or in the command line of a running
  process (where any other local process could read it).

.EXAMPLE
  .\scripts\install-service.ps1
  .\scripts\install-service.ps1 -Uninstall
#>
[CmdletBinding()]
param(
  [string]$TaskName = 'AgentRey-reyd',
  [switch]$Uninstall
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$stateDir = Join-Path $env:USERPROFILE '.agent-rey'
$envFile = Join-Path $stateDir 'reyd.env'
$launcher = Join-Path $stateDir 'start-reyd.ps1'
$logFile = Join-Path $stateDir 'reyd.out.log'

if ($Uninstall) {
  $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
  if ($null -eq $existing) {
    Write-Host "No scheduled task named $TaskName."
  } else {
    Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
    Write-Host "Removed scheduled task $TaskName." -ForegroundColor Green
  }
  Write-Host "Left $envFile in place (it holds your password). Delete it manually if you want it gone."
  exit 0
}

# ---- prerequisites ----

$node = (Get-Command node -ErrorAction SilentlyContinue).Source
if ($null -eq $node) { throw 'node is not on PATH. Install Node.js 22+ first.' }

$daemonEntry = Join-Path $repoRoot 'packages\daemon\dist\bin\reyd.js'
if (-not (Test-Path $daemonEntry)) {
  Write-Host 'The daemon is not built yet. Building…' -ForegroundColor Yellow
  Push-Location $repoRoot
  try {
    & pnpm --filter @agent-rey/daemon build
    if ($LASTEXITCODE -ne 0) { throw 'daemon build failed' }
  } finally {
    Pop-Location
  }
}
if (-not (Test-Path $daemonEntry)) { throw "Expected $daemonEntry after build, but it is missing." }

New-Item -ItemType Directory -Force -Path $stateDir | Out-Null

# ---- password ----

if (-not (Test-Path $envFile)) {
  Write-Host ''
  Write-Host 'Set a password for Agent Rey.' -ForegroundColor Cyan
  Write-Host 'Anyone who has it gets an agent with shell access to this machine, so make it long and unique.'
  # Windows PowerShell 5.1 runs on .NET Framework, where the static
  # RandomNumberGenerator::GetBytes(int) overload does not exist — it is .NET Core
  # only. Create() + GetBytes(buffer) works on both.
  $rngBytes = New-Object byte[] 24
  $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
  try { $rng.GetBytes($rngBytes) } finally { $rng.Dispose() }
  $suggested = [Convert]::ToBase64String($rngBytes) -replace '\+', '-' -replace '/', '_' -replace '=', ''
  if ($suggested.Length -lt 20) { throw "Failed to generate a password (got $($suggested.Length) chars)." }
  Write-Host ''
  Write-Host "  Suggested: $suggested"
  Write-Host ''
  $entered = Read-Host 'Password (blank to use the suggestion)'
  $password = if ([string]::IsNullOrWhiteSpace($entered)) { $suggested } else { $entered }

  $roots = Read-Host "Project roots (blank for $env:USERPROFILE\Documents\Work\Projects)"
  if ([string]::IsNullOrWhiteSpace($roots)) { $roots = Join-Path $env:USERPROFILE 'Documents\Work\Projects' }

  @(
    "REY_PASSWORD=$password",
    "REY_PROJECT_ROOTS=$roots",
    'REY_HOST=127.0.0.1',
    'REY_PORT=8787',
    'REY_CHECKPOINTING=1'
  ) | Set-Content -Path $envFile -Encoding utf8

  # Owner-only ACL: this file is the credential.
  $acl = Get-Acl $envFile
  $acl.SetAccessRuleProtection($true, $false)
  $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
    "$env:USERDOMAIN\$env:USERNAME", 'FullControl', 'Allow')
  $acl.SetAccessRule($rule)
  Set-Acl -Path $envFile -AclObject $acl

  Write-Host ''
  Write-Host "Wrote $envFile (readable only by you)." -ForegroundColor Green
} else {
  Write-Host "Using existing $envFile"
}

# ---- launcher ----
# A wrapper script keeps the password out of the task's command line: the task
# runs this file, and this file reads the env file itself.

@"
# Generated by scripts/install-service.ps1 — edit $envFile instead.
`$ErrorActionPreference = 'Stop'
Get-Content '$envFile' | ForEach-Object {
  if (`$_ -match '^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(.*)$') {
    [Environment]::SetEnvironmentVariable(`$matches[1], `$matches[2].Trim(), 'Process')
  }
}
Set-Location '$repoRoot'
& '$node' '$daemonEntry' *>> '$logFile'
"@ | Set-Content -Path $launcher -Encoding utf8

# ---- scheduled task ----

$action = New-ScheduledTaskAction `
  -Execute 'powershell.exe' `
  -Argument "-NoProfile -NonInteractive -WindowStyle Hidden -ExecutionPolicy Bypass -File `"$launcher`""

$trigger = New-ScheduledTaskTrigger -AtLogOn -User "$env:USERDOMAIN\$env:USERNAME"

$settings = New-ScheduledTaskSettingsSet `
  -AllowStartIfOnBatteries `
  -DontStopIfGoingOnBatteries `
  -StartWhenAvailable `
  -RestartCount 3 `
  -RestartInterval (New-TimeSpan -Minutes 1) `
  -ExecutionTimeLimit ([TimeSpan]::Zero)

$principal = New-ScheduledTaskPrincipal `
  -UserId "$env:USERDOMAIN\$env:USERNAME" `
  -LogonType Interactive `
  -RunLevel Limited

if (Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue) {
  Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
}

Register-ScheduledTask `
  -TaskName $TaskName `
  -Action $action `
  -Trigger $trigger `
  -Settings $settings `
  -Principal $principal `
  -Description 'Agent Rey daemon (reyd) — drives local Claude Code sessions for the mobile app.' | Out-Null

Write-Host ''
Write-Host "Registered scheduled task $TaskName (runs at your login)." -ForegroundColor Green
Write-Host ''
Write-Host 'Start it now:'
Write-Host "  Start-ScheduledTask -TaskName $TaskName"
Write-Host ''
Write-Host 'Check it:'
Write-Host '  curl http://127.0.0.1:8787/health'
Write-Host "  Get-Content '$logFile' -Tail 20"
Write-Host ''
Write-Host 'Then expose it to your tailnet and pair your phone:'
Write-Host '  .\scripts\setup-tailscale.ps1'
Write-Host '  node scripts\pair.mjs'
Write-Host ''
Write-Host "Remove with:  .\scripts\install-service.ps1 -Uninstall"
